### ISSUE TITLE
Error Building PKG on RHEL 6 for sensu-0.20.6

### ISSUE THREAD

**Issue by sureshsubramaniam** [sensu/sensu-build#137]
I am getting the below error when using the sensu-build for building rpm on RHEL 6
/usr/local/rvm/gems/ruby-2.1.5/gems/backports-2.6.2/lib/backports/tools.rb:265:in []': no implicit conversion of Symbol into Integer (TypeError) from /usr/local/rvm/gems/ruby-2.1.5/gems/backports-2.6.2/lib/backports/tools.rb:265:incombine_mode_and_option'
from /usr/local/rvm/gems/ruby-2.1.5/gems/backports-2.6.2/lib/backports/1.9.1/io.rb:18:in open_with_options_hash' from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1402:inblock in copy_file'
from /usr/local/rvm/gems/ruby-2.1.5/gems/backports-2.6.2/lib/backports/1.9.1/io.rb:21:in block in open_with_options_hash' from /usr/local/rvm/gems/ruby-2.1.5/gems/backports-2.6.2/lib/backports/1.9.1/io.rb:21:inopen'
from /usr/local/rvm/gems/ruby-2.1.5/gems/backports-2.6.2/lib/backports/1.9.1/io.rb:21:in open_with_options_hash' from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1401:incopy_file'
from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:483:in copy_file' from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:400:inblock in cp'
from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1579:in block in fu_each_src_dest' from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1595:infu_each_src_dest0'
from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1577:in fu_each_src_dest' from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:399:incp'
from /usr/local/rvm/gems/ruby-2.1.5/gems/fpm-0.4.26/lib/fpm/package/rpm.rb:234:in block in output' from /usr/local/rvm/gems/ruby-2.1.5/gems/fpm-0.4.26/lib/fpm/package/rpm.rb:232:ineach'
from /usr/local/rvm/gems/ruby-2.1.5/gems/fpm-0.4.26/lib/fpm/package/rpm.rb:232:in output' from /usr/local/rvm/gems/ruby-2.1.5/gems/fpm-0.4.26/lib/fpm/command.rb:408:inexecute'
from /usr/local/rvm/gems/ruby-2.1.5/gems/clamp-0.3.1/lib/clamp/command.rb:64:in run' from /usr/local/rvm/gems/ruby-2.1.5/gems/clamp-0.3.1/lib/clamp/command.rb:126:inrun'
from /usr/local/rvm/gems/ruby-2.1.5/gems/fpm-0.4.26/bin/fpm:8:in <top (required)>' from /usr/local/rvm/gems/ruby-2.1.5/bin/fpm:23:inload'
from /usr/local/rvm/gems/ruby-2.1.5/bin/fpm:23:in <main>' from /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:ineval'
from /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in <main>' rake aborted! Command failed with status (1): [fpm -s dir -t rpm -a x86_64 -n sensu -v 0.20.6 --iteration 1 --url 'http://sensuapp.org' --description 'A monitoring framework that aims to be simple, malleable, and scalable.' --license 'MIT License' --vendor 'Heavy Water Operations, LLC.' --category 'Monitoring' --maintainer 'Sensu Helpdesk <helpdesk@sensuapp.com>' --before-install pkg_scripts/rpm/pre --after-install pkg_scripts/rpm/post --before-remove pkg_scripts/rpm/preun --after-remove pkg_scripts/rpm/postun --config-files /etc/sensu/config.json.example --config-files /etc/sensu/conf.d/README.md --config-files /etc/logrotate.d/sensu --config-files /etc/default/sensu /etc/sensu/config.json.example /etc/sensu/conf.d/README.md /etc/logrotate.d/sensu /etc/default/sensu /opt/sensu /usr/share/sensu /var/log/sensu /etc/sensu/plugins /etc/sensu/mutators /etc/sensu/handlers /etc/sensu/extensions /etc/init.d/sensu-service /etc/init.d/sensu-api /etc/init.d/sensu-client /etc/init.d/sensu-server]. /usr/local/rvm/gems/ruby-2.1.5/gems/bunchr-0.1.6/lib/bunchr/utils.rb:21:insh'
/usr/local/rvm/gems/ruby-2.1.5/gems/bunchr-0.1.6/lib/bunchr/packages.rb:98:in block in define_build_rpm' /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:ineval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `

'
Tasks: TOP => default => packages:sensu => packages:sensu:default => packages:sensu:done => packages:sensu:build => packages:sensu:build_rpm
(See full trace by running task with --trace)

**Comment by sureshsubramaniam** [comment]
I am getting the below error when using the sensu-build for building rpm on RHEL 6
/usr/local/rvm/gems/ruby-2.1.5/gems/backports-2.6.2/lib/backports/tools.rb:265:in `[]': no implicit conversion of Symbol into Integer (TypeError)
        from /usr/local/rvm/gems/ruby-2.1.5/gems/backports-2.6.2/lib/backports/tools.rb:265:in `combine_mode_and_option'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/backports-2.6.2/lib/backports/1.9.1/io.rb:18:in `open_with_options_hash'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1402:in `block in copy_file'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/backports-2.6.2/lib/backports/1.9.1/io.rb:21:in `block in open_with_options_hash'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/backports-2.6.2/lib/backports/1.9.1/io.rb:21:in `open'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/backports-2.6.2/lib/backports/1.9.1/io.rb:21:in `open_with_options_hash'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1401:in `copy_file'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:483:in `copy_file'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:400:in `block in cp'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1595:in `fu_each_src_dest0'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
        from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/fpm-0.4.26/lib/fpm/package/rpm.rb:234:in `block in output'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/fpm-0.4.26/lib/fpm/package/rpm.rb:232:in `each'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/fpm-0.4.26/lib/fpm/package/rpm.rb:232:in `output'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/fpm-0.4.26/lib/fpm/command.rb:408:in `execute'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/clamp-0.3.1/lib/clamp/command.rb:64:in `run'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/clamp-0.3.1/lib/clamp/command.rb:126:in `run'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/fpm-0.4.26/bin/fpm:8:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.5/bin/fpm:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.5/bin/fpm:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
rake aborted!
Command failed with status (1): [fpm -s dir -t rpm -a x86_64 -n sensu -v 0.20.6 --iteration 1 --url 'http://sensuapp.org' --description 'A monitoring framework that aims to be simple, malleable, and scalable.' --license 'MIT License' --vendor 'Heavy Water Operations, LLC.' --category 'Monitoring' --maintainer 'Sensu Helpdesk <helpdesk@sensuapp.com>' --before-install pkg_scripts/rpm/pre --after-install pkg_scripts/rpm/post --before-remove pkg_scripts/rpm/preun --after-remove pkg_scripts/rpm/postun --config-files /etc/sensu/config.json.example --config-files /etc/sensu/conf.d/README.md --config-files /etc/logrotate.d/sensu --config-files /etc/default/sensu /etc/sensu/config.json.example /etc/sensu/conf.d/README.md /etc/logrotate.d/sensu /etc/default/sensu /opt/sensu /usr/share/sensu /var/log/sensu /etc/sensu/plugins /etc/sensu/mutators /etc/sensu/handlers /etc/sensu/extensions /etc/init.d/sensu-service /etc/init.d/sensu-api /etc/init.d/sensu-client /etc/init.d/sensu-server].
/usr/local/rvm/gems/ruby-2.1.5/gems/bunchr-0.1.6/lib/bunchr/utils.rb:21:in `sh'
/usr/local/rvm/gems/ruby-2.1.5/gems/bunchr-0.1.6/lib/bunchr/packages.rb:98:in `block in define_build_rpm'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => packages:sensu => packages:sensu:default => packages:sensu:done => packages:sensu:build => packages:sensu:build_rpm
(See full trace by running task with --trace)

**Comment by sureshsubramaniam** [comment]
seems to be issue with the ruby used, after using the ruby-2.0.0-p353, i can see the packages are being built successfully. Initially i used ruby 2.1.5p273, which resulted in the errors
