### ISSUE TITLE
restarts too fast

### ISSUE THREAD

**Issue by petere** [sensu/sensu-build#95]
I'm on CentOS 6.  Every so often, when `sensu-client` is restarted, it stops, then fails to start, leaving a message like this in the log:

```
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:868:in `open_udp_socket': no datagram socket (RuntimeError)
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:868:in `open_datagram_socket'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/lib/sensu/client.rb:223:in `setup_sockets'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/lib/sensu/client.rb:248:in `start'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/lib/sensu/client.rb:13:in `block in run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `call'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/lib/sensu/client.rb:12:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/bin/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:23:in `load'
        from /opt/sensu/bin/sensu-client:23:in `<main>'
```

It looks like it needs a moment until the kernel frees the socket.

Maybe a simple `sleep 1` in the init script would help?

Alternatively, try the starting in a loop a few times?

**Comment by mwdand** [comment]
i'm having the same issue, centos 7 client.  what am i supposed to do?

**Comment by joshzitting** [comment]
Yep I had this issue too on Ubnutn 12.04 clients. I have seen it on about 8-10 hosts in my env in the past week.

**Comment by mwdand** [comment]
What fixed it for you?

**Comment by joshzitting** [comment]
Nothing has fixed it. To get sensu working again initially I restarted the hosts… But on the last 2 machines (similar to the comments above) I searched for processes that were trying to report to sensu.. ps aux | grep sensu and then I killed them. pkill -9 -f sensu then I restarted the client and it worked just fine. 
so I think the port is stuck open because my checks that are in process are trying to send data to the sensu port.

**Comment by akammerer11** [comment]
We've had this issue and just hacked two scripts to call from a check.  First script nohups the second script which sleeps and issues restart a few seconds later.  Has worked well for us.

```
#sensu_restart - called in the check
#!/bin/bash
#restart sensu server via nohup and sleep commands
nohup /xxx/xxx/xxx/./sensu_sleep_restart.sh > /dev/null 2>&1 < /dev/null &
sleep 1
echo "success"
exit 0
```
actual restarter
```
#!/bin/bash
sleep 10
/etc/init.d/sensu-client restart
exit 0
```

Works for us on 0.16

**Comment by benh57** [comment]
This happens all the time for me -- very frustrating.

Its sad to see issues like this and others ignored while the project focuses on 'enterprise' products.

**Comment by portertech** [comment]
We can increase the current stop sleep as a "workaround", however, fixing the cause would be ideal. 

This should help https://github.com/sensu/sensu/issues/862#issuecomment-94973620

**Comment by portertech** [comment]
Pushed a PR https://github.com/sensu/sensu/pull/928

**Comment by portertech** [comment]
I pushed a PR with init script improvements, feedback would be appreciated https://github.com/sensu/sensu-build/pull/116

**Comment by calebhailey** [comment]
Closing due to inactivity, and because the linked PRs are all merged. Please feel free to create a new issue if this matter is not resolved. #monitoringlove
